export const reportsMock = [
    {
        id: 1,
        owner: "Grevtsov Mark",
        sendedTime: new Date(),
        recievedTime: new Date(),
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 2,
        owner: "Ayushiev Timur",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 3,
        owner: "Talankina Varvara",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'ERROR',
        file: [],
    },
    {
        id: 4,
        owner: "Kabanets Vladimir",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'PENDING',
        file: [],
    },
    {
        id: 1,
        owner: "Grevtsov Mark",
        sendedTime: new Date(),
        recievedTime: new Date(),
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 2,
        owner: "Ayushiev Timur",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 3,
        owner: "Talankina Varvara",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'ERROR',
        file: [],
    },
    {
        id: 4,
        owner: "Kabanets Vladimir",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'PENDING',
        file: [],
    },
    {
        id: 1,
        owner: "Grevtsov Mark",
        sendedTime: new Date(),
        recievedTime: new Date(),
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 2,
        owner: "Ayushiev Timur",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 3,
        owner: "Talankina Varvara",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'ERROR',
        file: [],
    },
    {
        id: 4,
        owner: "Kabanets Vladimir",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'PENDING',
        file: [],
    },
    {
        id: 1,
        owner: "Grevtsov Mark",
        sendedTime: new Date(),
        recievedTime: new Date(),
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 2,
        owner: "Ayushiev Timur",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 3,
        owner: "Talankina Varvara",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'ERROR',
        file: [],
    },
    {
        id: 4,
        owner: "Kabanets Vladimir",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'PENDING',
        file: [],
    },
];
