export const reportsMock = [
    {
        id: 1,
        owner: "Grevtsov Mark",
        sendedTime: new Date(),
        recievedTime: new Date(),
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 2,
        owner: "Ayushiev Timur",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 3,
        owner: "Talankina Varvara",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'ERROR',
        file: [],
    },
    {
        id: 4,
        owner: "Kabanets Vladimir",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'PENDING',
        file: [],
    },
    {
        id: 5,
        owner: "Grevtsov Mark",
        sendedTime: new Date(),
        recievedTime: new Date(),
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 6,
        owner: "Ayushiev Timur",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 7,
        owner: "Talankina Varvara",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'ERROR',
        file: [],
    },
    {
        id: 8,
        owner: "Kabanets Vladimir",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'PENDING',
        file: [],
    },
    {
        id: 9,
        owner: "Grevtsov Mark",
        sendedTime: new Date(),
        recievedTime: new Date(),
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 10,
        owner: "Ayushiev Timur",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "karina ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 11,
        owner: "Talankina Varvara",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'ERROR',
        file: [],
    },
    {
        id: 12,
        owner: "Kabanets Vladimir",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'PENDING',
        file: [],
    },
    {
        id: 13,
        owner: "Grevtsov Mark",
        sendedTime: new Date(),
        recievedTime: new Date(),
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 14,
        owner: "Ayushiev Timur",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'SUCCESS',
        file: [],
    },
    {
        id: 15,
        owner: "Talankina Varvara",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Lorem ipsum dolorem sit amet",
        status: 'ERROR',
        file: [],
    },
    {
        id: 16,
        owner: "Kabanets Vladimir",
        sendedTime: new Date(),
        recievedTime: undefined,
        payload: "Karina dolorem sit amet",
        status: 'PENDING',
        file: [],
    },
];
